general_configuration:
  retargeting_freq: 10.0
motion_adaption:
  # name of this adaption
  adaption_name: "robosem_head_adaption"
  # adaption type (no_adaption, trans_rot_adaption)
  adaption_type: "trans_rot_adaption"
  # reference frame of the input motion
  input_ref_frame: "input_ref"
  # retargeted endpoints 
  input_endpts: ["head_input"]
  # reference frame of the target system
  target_ref_frame: "base_link"
  # endpoints of the target system
  target_endpts: ["head_link"]
  # names for the endpoint goals
  goal_endpts: ["head_goal_link"]
  # applied rotational correction for the input motion
  input_correction: 
    roll: 0.0
    pitch: 1.5707
    yaw: 0.0
kinematics:
  # parameter name which holds the URDF robot model description
  robot_model_description_name: "/robosem/robot_description"
  # name of all endpoints involved in the IK calculations
  endpt_names: ["head_link"]
  # Maximum precision for the IK calculation in meter
  epsilon: 0.01
  # Maximum iterations for the IK calculation
  max_iterations: 10
  # Damping factor for the IK velocity solver
  lambda: 0.01
  # Frequency of IK calls - used for velocity limiting - smae as retargeting_freq TODO: sync
  ik_call_frequency: 10
  # Factor used for determining the maximum joint velocity (is scaled by ik_call_frequency)
  q_dot_max_factor: 1.0
  # Factor used for determining the minimum joint velocity (is scaled by ik_call_frequency)
  q_dot_min_factor: 0.3
  # Factor used for determining the maximum translational end point velocity (is scaled by ik_call_frequency)
  x_dot_trans_max_factor: 1.0 
  # Factor used for determining the minimum translational end point velocity (is scaled by ik_call_frequency)
  x_dot_trans_min_factor: 1.0
  # Factor used for determining the maximum rotational end point velocity (is scaled by ik_call_frequency)
  x_dot_rot_max_factor: 3.14
  # Factor used for determining the minimum rotational end point velocity (is scaled by ik_call_frequency)
  x_dot_rot_min_factor: 3.14
  # Factor used for low pass filtering - applied when all end points are considered resting
  low_pass_factor: 1.0
  # Matrix for task space weights for the IK velocity solver (6 x #end points)
  task_space_weights: [[0.0, 0.0, 0.0, 0.0, 1.0, 1.0]]
  # Matrix of joint weights for the IK velocity solver (#joints x #joints)
  joint_space_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]